<a href="https://colab.research.google.com/github/Saurabh5240/Python-Libraries/blob/main/Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy Tutorial


In [ ]:
   import numpy as np

List vs Numpy

In [ ]:
from time import process_time


In [ ]:
list = [i for i in range(10000)]

start_time = process_time()

list = [i+5 for i in list]

end_time = process_time()

print(end_time - start_time)


0.0014779960000002035


In [ ]:
np_array = np.array([i for i in range(10000)])
start_time = process_time()
np_array += 5
end_time = process_time()
print(end_time - start_time)


0.0001227930000009536


In [ ]:
np_array = np.array([1,2,3,4,5])

print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
a = np.array([1,2,3,4,5])
print(a)
a.shape


[1 2 3 4 5]


(5,)

In [ ]:
b = np.array([(1,2,3,4),(5,6,7,8),(9,10,11,12)])
print(b)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
b.shape

(3, 4)

In [ ]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)
#if not mentioned data dtype default will be integer
print(c[0][0])


[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]
1.0


Initial Placeholders

In [ ]:
#creating array of all zeros
x = np.zeros((2,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#creating array of all ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#creating array of all particular values
z = np.full((3,3),69)
print(z)

[[69 69 69]
 [69 69 69]
 [69 69 69]]


In [ ]:
#creating an identity matrix
i = np.eye(4)
print(i)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#creating a array with random values
array1 = np.random.random((3,3))  #gives values between 0 and 1
print(array1)

[[0.48620055 0.15108685 0.84401229]
 [0.56671803 0.17140306 0.6254803 ]
 [0.95927685 0.2413049  0.06464676]]


In [ ]:
#creating a random int array within a range
array2 = np.random.randint(1,100,(3,3))
print(array2)

[[ 9 23 25]
 [95 57  5]
 [53 40 21]]


In [ ]:
#create a array of evenly spaced values and steps to be taken
e = np.linspace(10,30,6) #here the no of values we want is mentioned
f= np.arange(10,30,6)  #this gives the space to be jumped
print(e)
print(f)

[10. 14. 18. 22. 26. 30.]
[10 16 22 28]


In [ ]:
#to covert list into array
list1 = [1,2,3,4,5]
num = 10
array1 = np.asarray(num)
num_array = np.asarray(list1)
print(num_array)
print(array1)
type(list1)

[1 2 3 4 5]
10


list

Analysis of numpy array


In [ ]:
c = np.random.randint(1,100,(4,4))
print(c)

[[ 1 98 34 74]
 [16 15 61 45]
 [89 98 23 75]
 [50 85 26 75]]


In [ ]:
#To get dimensions , no of dimensions , size or number of elements,data type
print(c.shape)
print(c.ndim)
print(c.size)
print(c.dtype)


(4, 4)
2
16
int64


In [ ]:
a = np.random.randint(1,10,(4,4))
b = np.random.randint(1,10,(4,4))
print(a)
print(b)


[[8 6 1 5]
 [9 2 5 5]
 [9 7 3 3]
 [7 5 2 6]]
[[1 5 1 5]
 [1 2 8 5]
 [6 7 3 9]
 [8 7 1 7]]


In [ ]:
#For elemet wise operations
print(a+b)
print(a-b)
print(a*b)
print(a/b)

#can also be done by
print(np.add(a,b))   #same np.subtract()  np.multiply() np.divide()

[[ 9 11  2 10]
 [10  4 13 10]
 [15 14  6 12]
 [15 12  3 13]]
[[ 7  1  0  0]
 [ 8  0 -3  0]
 [ 3  0  0 -6]
 [-1 -2  1 -1]]
[[ 8 30  1 25]
 [ 9  4 40 25]
 [54 49  9 27]
 [56 35  2 42]]
[[8.         1.2        1.         1.        ]
 [9.         1.         0.625      1.        ]
 [1.5        1.         1.         0.33333333]
 [0.875      0.71428571 2.         0.85714286]]
[[ 9 11  2 10]
 [10  4 13 10]
 [15 14  6 12]
 [15 12  3 13]]


In [ ]:
#For matrix like operations
m1 = np.matrix(a)
m2 = np.matrix(b)
print(m1*m2)
type(m1)

[[ 60  94  64 114]
 [ 81 119  45 135]
 [ 58 101  77 128]
 [ 72 101  59 120]]


numpy.matrix

In [ ]:
#For direct matrix multiplication
print(a@b)    #can also use np.dot(a,b)  for matrix like multiplication

[[ 60  94  64 114]
 [ 81 119  45 135]
 [ 58 101  77 128]
 [ 72 101  59 120]]


In [ ]:
list1 = [1,2,3,4]
list2 = [5,6,7,8]
print(list1+list2)  #list is concated or joined


[1, 2, 3, 4, 5, 6, 7, 8]


Array manipulation

In [ ]:
a = np.random.randint(1,10,(2,3))
print(a, "  ",a.shape)

[[7 5 1]
 [6 6 6]]    (2, 3)


In [ ]:
#to find transpose -2 methods
trans1 = np.transpose(a)
trans2 = a.T
print(trans1)
print(trans2)
print(trans1.shape,"  ",trans2.shape)

[[7 6]
 [5 6]
 [1 6]]
[[7 6]
 [5 6]
 [1 6]]
(3, 2)    (3, 2)


In [ ]:
#Reshaping a array

a = np.random.randint(1,50,(2,4))
print(a)
print(a.shape)

[[ 4 42 12 18]
 [35 35 49 11]]
(2, 4)


In [ ]:
b = a.reshape(4,2)     #while reshaping size must be same
print(b)
print(b.shape)

[[ 4 42]
 [12 18]
 [35 35]
 [49 11]]
(4, 2)
